
services:
  ollama:
    build:
      context: ./ollama
    platform: linux/amd64 # Ensure compatibility on VM
    container_name: ollama
    ports:
      - "11434:11434" # Expose Ollama API port
    volumes:
      - ollama_models:/root/.ollama # Persist models between runs
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: /bin/sh
    command: -c " 
      ollama serve &
      sleep 5 &&
      if ! ollama list | grep -q qwen3-coder:30b; then
        echo 'Pulling qwen3-coder:30b...';
        ollama pull qwen3-coder:30b;
      else
        echo 'Model qwen3-coder:30b already exists.';
      fi &&
      tail -f /dev/null
      " # Start Ollama server and ensure model is pulled
    restart: unless-stopped

  streamlit:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    platform: linux/amd64
    container_name: streamlit
    ports:
      - "8091:8501" # Expose Streamlit app port, port 8091 is open on Tan Lab VM
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama # Ollama will successfully start before Streamlit
    restart: unless-stopped

volumes:
  ollama_models:
    name: irae_llm_ollama_models
        


